### ISSUE TITLE
ALEX - a functioning platform on Stacks that efficiently connects crypto financial participants

### ISSUE THREAD

**Issue by fiftyeightandeight** [stacksgov/Stacks-Grant-Launchpad#143]
## Background

Stacks is an open-source network of decentralized apps and smart contracts built on Bitcoin. Stacks unleashes Bitcoin’s full potential as a programmable base layer.
Stacks makes it then possible to access the liquidity, power, and safety of Bitcoin’s 1tn dollar blockchain.
Stacks 2.0 being released only recently, however, there is currently a lack of DeFi primitives and ecosystem to unlock the full potential of Bitcoin.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/443225/120918288-4b1e8080-c6e6-11eb-8307-5d3db5fc7384.png">
Fig 1: Stacks currently lacks DeFi primitives and ecosystem to unlock the full potential of Bitcoin

## Project Overview

Think of us as [Compound](https://compound.finance) / [AAVE](https://aave.com) with underlying technology like [Balancer](https://balancer.fi), but user experience of [Robinhood](https://www.robinhood.com).

At ALEX, you can 
- Lend your BTC and earn 
- Borrow BTC
- Mitigate risk with BTC short positions
- Maximize upside with BTC leveraged long positions

<img width="369" alt="image" src="https://user-images.githubusercontent.com/443225/120918450-15c66280-c6e7-11eb-9950-5ccab7f2c0d5.png">
Fig 2: ALEX aims to build DeFi primitives that Stacks need to grow its ecosystem

Our initial focus (v1) is
- Build DeFi primitives targeting developers looking to build ecosystem on Stacks, and
- Simplify the user experience going from(to) CeFi to(from) DeFi to attract non-developers, broadening the Stacks user base.

## Scope

A number of Clarity smart contracts will be built on the core concept of Yield Tokens ("ayTokens"). Yield Tokens allow term lending with fixed APY.

<img width="536" alt="image" src="https://user-images.githubusercontent.com/443225/120919614-18c45180-c6ed-11eb-8252-81d5bbf09f9d.png">
Fig 3: Yield Tokens allow term lending with fixed APY

### Lending at fixed yield for a fixed term
- Buying of ayToken (against Token) equates to lending of Token at the rate implied by the price of ayToken until T.
- Holding ayToken until T allows the holder to accrue, with certainty, at a fixed rate (as implied by the price at which holder bought ayToken).
- Selling of ayToken before T could result in a profit or loss, depending on the prevailing price of ayToken.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/443225/120918675-27f4d080-c6e8-11eb-99a7-7a2b9b398123.png">
Fig 4: Buying and selling of Yield Tokens allows the efficient price discovery

### Borrowing at fixed yield for a fixed term
- Minting of ayToken against collateral assets and selling of ayToken against Token equates to the borrowing of Token at the rate implied by the price at which ayToken was sold.
- Loan-to-Value (“LTV”) is the ratio of the value of the tokens borrowed and the value of the collateral assets.
- Liquidation occurs if the LTV of a loan reaches the Maximum Loan-to-Value (“Max LTV”).

<img width="632" alt="image" src="https://user-images.githubusercontent.com/73505363/122315206-30e96b80-cf4c-11eb-9585-a172b2085bf2.png">
Fig 5: Illustration of borrowing lifecycle

### Automated Market Making designed for lending / borrowing protocols
The borrow rates embedded in ayTokens are determined using an automated market making formula, for example using the constant power sum formula between the balance of the Yield Tokens and that of collateral asset, following Yield Space (https://yield.is/YieldSpace.pdf), suitably modified to allow for capital efficiency following Uniswap v3 (https://uniswap.org/whitepaper-v3.pdf).

### Platform Architecture that supports ecosystem development

<img width="843" alt="image" src="https://user-images.githubusercontent.com/443225/120918758-9c2f7400-c6e8-11eb-9bbd-d940c6c397b6.png">
Fig 6: ALEX platform is designed to allow for implementation of arbitrary trading strategies

## Deliverable 
Low-fi mock-up (mocknet and local repo cloning) of the ALEX DeFi platform, which enables users to lend & earn BTC, borrow BTC, mitigate risk with BTC short positions, and maximize upside with BTC-leveraged long positions.

### Budget & Milestones
Total requested grant for this deliverable = $30,000
Estimated time of completion: Early July

### Milestone 1
We like the design of [Balancer V2](https://docs.balancer.fi) and are borrowing heavily from their ideas to design our platform to allow for implementation of arbitrary trading strategies.

Equation abstracts rebalancing and market making logic, while Pool encapsulates the value of a strategy.
Pool abstraction allows aggregation of the assets of all ALEX pools into a single vault, bringing many advantages over traditional DEX architecture.

Key base component specifications (shown in diagram below), which include:
- **Vault** specification: Vault holds and manages the assets of all ALEX pools. The design has many advantages over the traditional DEX architecture; it enables abstraction of pool logic, significantly cheaper multi-leg trades, high frequency trading, flash loans, and more.
- **Pool** specification: Pools handle the logic of dynamic trading strategies, whose token rebalancing are then handled by Vault. Pools consist of the Strategy Token whose value is driven by Collateral Tokens. Rebalancing logic is driven by Equation. Pool issues Pool Token to liquidity provider, representing a proportional ownership of that Pool
- **Equation** specification: Equation triggers Pool rebalancing. This allows creation of any arbitrary rebalancing strategies to be deployed as a pool.

<img src="https://yuml.me/alexgo/alex-v1-class.svg">

Fig 7: Class Diagram (work in progress, subject to change)

<img src="https://yuml.me/alexgo/Alex-v1-back-end-usecase.svg">

Fig 8: Back-end Use Case (work in progress, subject to change)

### Milestone 2
Low-fi mock-up that users can engage with, which includes:

- User dashboard that displays the following:
    * I see My Balance, summary list of all tokens I hold.
    * I see My Borrowing, summary list of all borrowings I have.
    * I can click on each token for more details.
    * Those Yield Tokens "in the money" will be highlighted.
    * Those borrowings close to liquidation will be highlighted.
    * Upon clicking a token (non Yield Token), I see my current balance, associated Yield Tokens I hold, and maximum I can borrow using the balance as the collateral.
    * Upon clicking on an Yield Token, I see my current balance, and maximum I can borrow using the balance as the collateral.
    * Upon clicking on any borrowing, I see my current balance, current LTV, maximum LTV, Liquidation penalty, maximum I can borrow further, maximum I can repay, maximum I can top-up, and the list of Yield Tokens I can roll into.
- Lending capabilities:
    * I see My Deposits, summary list of Yield Tokens I hold, which I can buy, sell, or borrow against.
    * I see Available Deposits, summary list of available Yield Tokens I can buy, together with max amount I can buy.
- Borrowing capabilities:
    * I see My Borrowings, summary list of all borrowings I have, which I can borrow more, repay or top-up.
    * I see Available Borrowings, summary list of all available Yield Tokens I can mint, together with max amount I can mint.
    * I can top-up Collateral any time or when I receive Max LTV notice.
    * If I receive Max LTV notice and do nothing, Collateral will be liquidated to burn Yield Tokens and return residuals.

![](https://yuml.me/alexgo/Alex-v1-use.svg)
Fig 9: Use Cases (work in progress, subject to change)

![](https://yuml.me/alexgo/Alex-v1-activity.svg)
Fig 10: Activity Diagram (work in progress, subject to change)

**Comment by RaffiSapire** [comment]
Hi @fiftyeightandeight - we are excited to support this and you all. It will be a great contribution to the community. I'd like to provide some help scoping this out a bit more. We have our committee meeting tomorrow in case you're able to provide a response before then. 

1. M1 - can you clarify, what is the output here? What will a user be able to do after M1? Said another way, how do we know when M1 is complete? Is it that the components are built, so we would be able to review the repo? What has been built to date already? 
2. M2 - Can you break this down a bit further and add another milestone, M3 based on how you anticipate to roll out features? Which features, if any have been built already? 
3. Lastly, based on time it will take to build, can you please break down the grant request to each of 3 milestones? 
4. Also, wanted to confirm that this will be open source?

Thank you,
Raffi

**Comment by fiftyeightandeight** [comment]
Hi @RaffiSapire,

1. The deliverables are (a) the final Class Diagram (Fig 7) and (b) two whitepapers covering (i) platform architecture and (ii) key automated market making technologies developed. All will be available through https://docs.alexgo.io and https://github.com/alexgo-io/alex-v1. Please also review the two links for an overview of what has been built to date (and what will be built over time).
2. The deliverables are (c) the final Use Case / Activities Diagrams (Fig 8 and Fig 9) and (d) Figma prototype demonstrating the user experience. All will be available through https://docs.alexgo.io and https://github.com/alexgo-io/alex-v1. Please also review https://www.figma.com/proto/qYaw7UH9Rl8CS6i9Wf1NY6/ALEX-App?page-id=272%3A2&node-id=272%3A970&viewport=283%2C817%2C0.35857143998146057&scaling=scale-down for the current working version prototype.
3. We can assign (a) as M1, (b) as M2, (c)+(d) as M3, with $10,000 grant request to each.
4. All of the above will be open source (under MIT License).

Thank you.

**Comment by RaffiSapire** [comment]
Hi @fiftyeightandeight thank you, this grant is approved.

**Comment by fiftyeightandeight** [comment]
@RaffiSapire we signed the contract a few days ago. Please let us know if all good?

**Comment by fiftyeightandeight** [comment]
@RaffiSapire we are pleased to update that M1 is now completed.

- Class Diagram: https://docs.alexgo.io/protocol/diagrams/class-diagram
- Use Case: https://docs.alexgo.io/protocol/diagrams/protocol-use-case

!m1_complete

**Comment by fiftyeightandeight** [comment]
@RaffiSapire we are pleased to update that M2 is now completed.

- Platform architecture: https://docs.alexgo.io (excluding https://docs.alexgo.io/whitepaper/)
- Yield Token AMM whitepaper: https://docs.alexgo.io/whitepaper/automated-market-making-of-alex

!m2_complete

**Comment by fiftyeightandeight** [comment]
> Hi @RaffiSapire,
> 
> 1. The deliverables are (a) the final Class Diagram / Use Case (Fig 7 and Fig 8) and (b) two whitepapers covering (i) platform architecture and (ii) key automated market making technologies developed. All will be available through https://docs.alexgo.io and https://github.com/alexgo-io/alex-v1. Please also review the two links for an overview of what has been built to date (and what will be built over time).
> 2. The deliverables are (c) the final Use Case / Activities Diagrams (Fig 9 and Fig 10) and (d) Figma prototype demonstrating the user experience. All will be available through https://docs.alexgo.io and https://github.com/alexgo-io/alex-v1. Please also review https://www.figma.com/proto/qYaw7UH9Rl8CS6i9Wf1NY6/ALEX-App?page-id=272%3A2&node-id=272%3A970&viewport=283%2C817%2C0.35857143998146057&scaling=scale-down for the current working version prototype.
> 3. We can assign (a) as M1, (b) as M2, (c)+(d) as M3, with $10,000 grant request to each.
> 4. All of the above will be open source (under MIT License).
> 
> Thank you.

@RaffiSapire for M3, could we please consider revising the deliverables to a set of client-side javascript APIs that developers on Stacks can use to integrate/develop on ALEX? One can of course connect to contracts directly using stacks.js, but higher-level APIs that abstract away most (if not all) the plumbing associated with stacks.js will be useful/meaningful to the community (more so than the originally agreed M3 deliverables, in our view).

**Comment by jhammond2012** [comment]
Hi @fiftyeightandeight can you please comment on the milestone complete command again? Thanks!

**Comment by RaffiSapire** [comment]
Hi @fiftyeightandeight we reviewed and approve M1 and M2 being complete. Excited to see this to the finish line. Could you kindly please clarify what has and has not been delivered? The new M3 seems like more work than the original. Could we keep the prototype on top of the javascript API and  bump up the amount based on what you think is fair? Thanks and congrats!!

**Comment by fiftyeightandeight** [comment]
> Hi @fiftyeightandeight can you please comment on the milestone complete command again? Thanks!

!m1_complete
!m2_complete

**Comment by fiftyeightandeight** [comment]
!m1_complete

**Comment by fiftyeightandeight** [comment]
@RaffiSapire we reviewed carefully the current agreed deliverable of M3 and, while they are completed, we do not feel this actually has much value to the Stacks community (partly because we ourselves are going through some significant re-design of UX/UI). Therefore, we would be grateful if the Foundation could consider the following deliverable instead.

### M3
**Deliverable**: a suite of smart contracts that provide key functionalities of lending and borrowing as described on https://docs.alexgo.io/developers/smart-contracts/diagrams/class-diagram. The deliverable will be available on https://github.com/alexgo-io/alex-v1.
**Total requested grant** for this deliverable = $35,000
**Deliverable deadline**: end of Sep

- [ ] Weighted Equation ($5,000)
- [ ] Yield Token Equation ($5,000)
- [ ] Fixed Weight Pool ($5,000)
- [ ] Yield Token Pool ($5,000)
- [ ] Collateral Rebalancing Pool ($5,000)
- [ ] Liquidity Bootstrapping Pool ($5,000)
- [ ] Fixed Point Library ($5,000)

We would also like to expand the scope of grant to include the following milestones:

### M4
**Deliverable**: a whitepaper on Collateral Rebalancing Pool. The deliverable will be available on https://docs.alexgo.io/whitepaper/.
**Total requested grant** for this deliverable = $10,000
**Deliverable deadline**: end of Sep

### M5
**Deliverable**: an umbrella Javascript package that exports all the ALEX tools you need to start building on ALEX. The deliverable will be available on https://github.com/alexgo-io/alex.js.
**Total requested grant** for this deliverable = $30,000
**Deliverable deadline**: early Sep

- [ ] Contract Calls ($10,000): APIs for contract calls (`define-public`) and error handling
- [ ] Read-Only ($10,000): APIs for read-only functions (`define-read-only`) and error handling
- [ ] Transaction Status Watcher ($5,000): Event dispatcher listening on transaction status change
- [ ] Utils ($5,000): Helper functions useful for developers

![](https://user-images.githubusercontent.com/5652583/128288658-d8e53209-ae09-422b-af43-7307862e3ed2.png)

**Comment by fiftyeightandeight** [comment]
@RaffiSapire we would like the Foundation to consider adding the following as an additional milestone (i.e. M6).

**M6**: [ALEX Launchpad](https://github.com/alexgo-io/alex-v1/issues/79)

Would you please review and let us know? Thank you.

**Comment by jennymith** [comment]
> @RaffiSapire we reviewed carefully the current agreed deliverable of M3 and, while they are completed, we do not feel this actually has much value to the Stacks community (partly because we ourselves are going through some significant re-design of UX/UI). Therefore, we would be grateful if the Foundation could consider the following deliverable instead.
> ### M3
> 
> **Deliverable**: a suite of smart contracts that provide key functionalities of lending and borrowing as described on https://docs.alexgo.io/developers/smart-contracts/diagrams/class-diagram. The deliverable will be available on https://github.com/alexgo-io/alex-v1.
> **Total requested grant** for this deliverable = $30,000
> **Deliverable deadline**: end of Sep
> 
>     * [ ]  Weighted Equation ($5,000)
> 
>     * [ ]  Yield Token Equation ($5,000)
> 
>     * [ ]  Fixed Weight Pool ($5,000)
> 
>     * [ ]  Yield Token Pool ($5,000)
> 
>     * [ ]  Collateral Rebalancing Pool ($5,000)
> 
>     * [ ]  Fixed Point Library ($5,000)
> 
> 
> We would also like to expand the scope of grant to include the following milestones:
> ### M4
> 
> **Deliverable**: a whitepaper on Collateral Rebalancing Pool. The deliverable will be available on https://docs.alexgo.io/whitepaper/.
> **Total requested grant** for this deliverable = $10,000
> **Deliverable deadline**: end of Sep
> ### M5
> 
> **Deliverable**: an umbrella Javascript package that exports all the ALEX tools you need to start building on ALEX. The deliverable will be available on https://github.com/alexgo-io/alex.js.
> **Total requested grant** for this deliverable = $30,000
> **Deliverable deadline**: early Sep
> 
>     * [ ]  Contract Calls ($10,000): APIs for contract calls (`define-public`) and error handling
> 
>     * [ ]  Read-Only ($10,000): APIs for read-only functions (`define-read-only`) and error handling
> 
>     * [ ]  Transaction Status Watcher ($5,000): Event dispatcher listening on transaction status change
> 
>     * [ ]  Utils ($5,000): Helper functions useful for developers
> 
> 
> ![](https://user-images.githubusercontent.com/5652583/128288658-d8e53209-ae09-422b-af43-7307862e3ed2.png)

Hi @fiftyeightandeight, thanks for your proposal! In summary, we would prefer that you stick with the original M3 rather than pursuing the new M3 + M4 & M5. The main reason for this is that we believe a prototype could really help onboard users in the Stacks community not only to the ALEX platform, but to Stacks/Bitcoin DeFi in general. While a suite of smart contracts for developers could be helpful, engaging with potential users seems to be a more urgent priority at the moment. Plus, many of the smart contract capabilities you've listed already exist in some capacity in Stacks.js (though maybe not as simplified as you would like). More specific questions and in depth feedback below.

**Clarifying Questions:** 
- Are you saying that the [original version of M3](https://github.com/stacksgov/Stacks-Grants/issues/143#issuecomment-870189121) HAS been completed but you would prefer not to get funding for it? 
- Are you asking to fund two NEW milestones (M4 and M5) instead? 

**On M3:** It looks like many of the contracts you list in the revised M3 are already in progress on GitHub. (As you know, the grants program cannot fund previous work or work that has already begun.) Are you planning to make significant changes to these contracts that would warrant $5,000 each?

**On M4:** If the goal of the revised milestones is to help developers, what is the value of producing a whitepaper over standard documentation?

**On M5:** These are also functions that already exist in some capacity and may not warrant a new package right at this moment. Are you finding that many developers in the Stacks community are running into trouble with things like Clarity contract calls? If so, where are you seeing this discussion? Are they asking specifically for an API solution?

**Comment by fiftyeightandeight** [comment]
Hi @jennymith , 

> Are you saying that the original version of M3 HAS been completed but you would prefer not to get funding for it?

We are going through some significant re-design of the UX/UI prototype which depends on the final delivery of new milestones M3, M4 and M5. The reason why we said it, as it stood, might not have much value to the Stacks community was because we realised the prototype we completed (as the deliverable for M3 as originally agreed) would be subject to many changes.
Having said that, we also see your point in such a prototype helping onboard users not only to the ALEX platform, but also to Stacks/Bitcoin DeFi in general.
A good news is that, since our original proposal (of revising M3), we made some great progress to lock down the key details of the UX/UI design that wouldn't be affected even if implementation details change at the contract level (with help of `alex.js` - see below **M5**), so we think we can stick with the original M3.

> Are you asking to fund two NEW milestones (M4 and M5) instead?

Yes, given the above concern, we are asking to fund two new milestones.

On **new M3**, the initial scaffolding of the contracts is completed. The contracts, however, need to go through significant changes/optimisation to be run-time efficient, bug free, and secure, before we launch our testnet in early Oct.

On **new M4**, this is a must-have thought leadership paper and any serious DeFi developers will want to read and understand this. The whitepaper is an additional paper (after our [last paper](https://docs.alexgo.io/whitepaper/automated-market-making-of-alex)) we are looking to publish and contribute to the DeFi community that sets out **the mathematical framework for a collateralised fixed-yield/fixed-term lending pool without liquidation risk**. This will provide an academic paper-like rigorous treatment of the framework underpinning our collateral rebalancing pool (not some commercial "lite paper"). Collateral Rebalancing Pool is a new concept that does not currently exist in Ethereum DeFi and is possible only because of the unique features Stacks has (vs. Ethereum).

On **new M5**, this is not a re-hash of `stacks.js`, but a higher-level library that allows front-end developers to interact with contracts deployed at ALEX and encapsulates the lower-level calls to `stacks.js`. This is important for DeFi developer adoption of Stacks ecosystem and all of our early adopters (incl. other cohorts at Accelerator programme) ask for this. This also serves as a reference implementation for any Stacks smart contract developers looking to expose similar APIs to other front-end developers.

**Comment by RaffiSapire** [comment]
Hi @fiftyeightandeight thank you for your response. We discussed this at length for a second time with your responses as context, and we are going to stick with the originally approved Milestone 3, which you have completed, and we will disburse that capital today. We are going to pass on funding the additional proposed milestones. We are open to you submitting a new proposal, we'd suggest you review the [criteria](https://github.com/stacksgov/Stacks-Grants) listed here. As a committee we could not convince ourselves that the milestones you laid out meet those criteria sufficiently. You are welcome to submit new proposals in the future.

**Comment by will-at-stacks** [comment]
Hello and thank you for participating in the Stacks Foundation Grants Program!

We are in the process of migrating from GitHub to the new [Grants Dashboard](https://grants.stacks.org/). In order to complete your grant, you will need to submit any remaining Progress Review and/or Final Review requests through the Dashboard in order to receive your remaining payments.

- If you have questions about the Grants Dashboard in general please email [ambassadors@stacks.org](mailto:ambassadors@stacks.org).
- If you have questions regarding payments and/or contracts please email [payments@stacks.org](mailto:payments@stacks.org).

Lastly, please note we are marking this grant 'closed' on GitHub for organizational purposes, but it is still 'open' on the Grants Dashboard.

Thanks and we hope to continue to support your efforts with additional grants!

Best,
Will
